In [2]:
import pandas as pd
data={
    'Department':['HR','Sales','IT','Sales','IT','HR','Sales'],
    'Employee':['A','B','C','D','E','F','G'],
    'Salary':[50000,60000,45000,48000,70000,72000,71000],
    'Experience':[2,4,3,5,6,7,5]
}
df=pd.DataFrame(data)
print(df)

  Department Employee  Salary  Experience
0         HR        A   50000           2
1      Sales        B   60000           4
2         IT        C   45000           3
3      Sales        D   48000           5
4         IT        E   70000           6
5         HR        F   72000           7
6      Sales        G   71000           5

In [31]:
import pandas as pd
data={
    'Department':['HR','Sales','IT','Sales','IT','HR','Sales'],
    'Employee':['A','B','C','D','E','F','G'],
    'Salary':[50000,60000,45000,48000,70000,72000,71000],
    'Experience':[2,4,3,5,6,7,5]
}
df=pd.DataFrame(data)
print(df)

df.groupby(['Department','Experience']).sum()

df.groupby('Department').agg({
'Salary':'sum','Experience':'mean'
})

  Department Employee  Salary  Experience
0         HR        A   50000           2
1      Sales        B   60000           4
2         IT        C   45000           3
3      Sales        D   48000           5
4         IT        E   70000           6
5         HR        F   72000           7
6      Sales        G   71000           5

            Salary  Experience
Department
HR          122000    4.500000
IT          115000    4.500000
Sales       179000    4.666667

In [27]:
df.groupby('Department').agg({'Salary':'sum','Experience':'mean'})

            Salary  Experience
Department
HR          122000    4.500000
IT          115000    4.500000
Sales       179000    4.666667

In [5]:
df3=df.groupby('Experience').sum()
print(df3)

            Department Employee  Salary
Experience
2                   HR        A   50000
3                   IT        C   45000
4                Sales        B   60000
5           SalesSales       DG  119000
6                   IT        E   70000
7                   HR        F   72000

In [6]:
df.groupby('Department')['Salary'].sum()

Department
HR       122000
IT       115000
Sales    179000
Name: Salary, dtype: int64

In [7]:
df1=df.groupby(['Department','Experience']).sum()
print(df1)

                      Employee  Salary
Department Experience
HR         2                 A   50000
           7                 F   72000
IT         3                 C   45000
           6                 E   70000
Sales      4                 B   60000
           5                DG  119000

In [8]:
df2=df.groupby('Department').sum()
print(df2)

           Employee  Salary  Experience
Department
HR               AF  122000           9
IT               CE  115000           9
Sales           BDG  179000          14

In [24]:
df9=df['Dept_Avg_Salary']=df.groupby('Department')['Salary'].transform('mean')
print(df9)

0    61000.000000
1    59666.666667
2    57500.000000
3    59666.666667
4    57500.000000
5    61000.000000
6    59666.666667
Name: Salary, dtype: float64

In [29]:
# MEAN SALARY BY DEPARTMENT AND EXPERIENCE
df.pivot_table(
    values='Salary',
    index='Department',
    columns='Experience',
    aggfunc='mean'
)

Experience        2        3        4        5        6        7
Department
HR          50000.0      NaN      NaN      NaN      NaN  72000.0
IT              NaN  45000.0      NaN      NaN  70000.0      NaN
Sales           NaN      NaN  60000.0  59500.0      NaN      NaN

In [33]:
df.groupby(['Department','Experience']).sum()

                      Employee  Salary
Department Experience
HR         2                 A   50000
           7                 F   72000
IT         3                 C   45000
           6                 E   70000
Sales      4                 B   60000
           5                DG  119000

In [34]:
df5=df.groupby('Department')['Salary'].mean()
print(df5)

Department
HR       61000.000000
IT       57500.000000
Sales    59666.666667
Name: Salary, dtype: float64

In [36]:
df6=df.groupby('Department')['Employee'].count()
print(df6)

Department
HR       2
IT       2
Sales    3
Name: Employee, dtype: int64

In [37]:
df7=df.groupby('Department')['Salary'].agg(['sum','mean','std'])
print(df7)

               sum          mean           std
Department
HR          122000  61000.000000  15556.349186
IT          115000  57500.000000  17677.669530
Sales       179000  59666.666667  11503.622618

In [60]:
import pandas as pd

data = {
    "Field_ID": ["S001", "S002", "S003", "S004", "S005", "S006", "S007", "S008"],
    "Crops": ["Rice", "Cotton","Wheat", "Cotton", "Rice", "Wheat", "Cotton", "Rice"],
    "pH": [6.5, 7.2, 6.2, 7.5, 6.2, 7.2, 5.8, 6.7],
    "Production": [7.2, 4.8, 2.5, 3.5, 3.5, 8.5, 6.1, 7.2]
}

df = pd.DataFrame(data)
print(df)

  Field_ID   Crops   pH  Production
0     S001    Rice  6.5         7.2
1     S002  Cotton  7.2         4.8
2     S003   Wheat  6.2         2.5
3     S004  Cotton  7.5         3.5
4     S005    Rice  6.2         3.5
5     S006   Wheat  7.2         8.5
6     S007  Cotton  5.8         6.1
7     S008    Rice  6.7         7.2

In [61]:
df.groupby(['Crops','Production']).sum()

                   Field_ID    pH
Crops  Production
Cotton 3.5             S004   7.5
       4.8             S002   7.2
       6.1             S007   5.8
Rice   3.5             S005   6.2
       7.2         S001S008  13.2
Wheat  2.5             S003   6.2
       8.5             S006   7.2

In [62]:
df.groupby('Crops').agg({'Production':'sum','pH':'mean'})

        Production        pH
Crops
Cotton        14.4  6.833333
Rice          17.9  6.466667
Wheat         11.0  6.700000

In [63]:
df1=df.groupby(['Crops','Production']).sum()
print(df1)

                   Field_ID    pH
Crops  Production
Cotton 3.5             S004   7.5
       4.8             S002   7.2
       6.1             S007   5.8
Rice   3.5             S005   6.2
       7.2         S001S008  13.2
Wheat  2.5             S003   6.2
       8.5             S006   7.2

In [64]:
df2=df.groupby('Crops').sum()
print(df2)

            Field_ID    pH  Production
Crops
Cotton  S002S004S007  20.5        14.4
Rice    S001S005S008  19.4        17.9
Wheat       S003S006  13.4        11.0

In [65]:
df1=df.groupby(['Crops','pH']).sum()
print(df1)

           Field_ID  Production
Crops  pH
Cotton 5.8     S007         6.1
       7.2     S002         4.8
       7.5     S004         3.5
Rice   6.2     S005         3.5
       6.5     S001         7.2
       6.7     S008         7.2
Wheat  6.2     S003         2.5
       7.2     S006         8.5

In [67]:
df5=df.groupby('Crops')['Production'].mean()
print(df5)

Crops
Cotton    4.800000
Rice      5.966667
Wheat     5.500000
Name: Production, dtype: float64

In [68]:
df6=df.groupby('Crops')['Field_ID'].count()
print(df6)

Crops
Cotton    3
Rice      3
Wheat     2
Name: Field_ID, dtype: int64

In [69]:
df7=df.groupby('Crops')['Production'].agg(['sum','mean','std'])
print(df7)

         sum      mean       std
Crops
Cotton  14.4  4.800000  1.300000
Rice    17.9  5.966667  2.136196
Wheat   11.0  5.500000  4.242641

In [70]:
df9=df['Crops_avg_Production']=df.groupby('Crops')['Production'].transform('mean')
print(df9)

0    5.966667
1    4.800000
2    5.500000
3    4.800000
4    5.966667
5    5.500000
6    4.800000
7    5.966667
Name: Production, dtype: float64